// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ3GFI7QDrBO18XIdoXJ8wFb2d18gIRQQ',
    appId: '1:414659217522:web:b24d26c8333bd389bb1aeb',
    messagingSenderId: '414659217522',
    projectId: 'wanderlense-pc',
    authDomain: 'wanderlense-pc.firebaseapp.com',
    storageBucket: 'wanderlense-pc.firebasestorage.app',
    measurementId: 'G-NGHBGXHS61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj6inyyec2yLDhUzmT7dQY_bkAqsCv3XQ',
    appId: '1:414659217522:android:1207eb66d9e30a21bb1aeb',
    messagingSenderId: '414659217522',
    projectId: 'wanderlense-pc',
    storageBucket: 'wanderlense-pc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZKeL3XIvcKmx4cuwqkfXN46cG6uxPqWk',
    appId: '1:414659217522:ios:605c7d535af9bf31bb1aeb',
    messagingSenderId: '414659217522',
    projectId: 'wanderlense-pc',
    storageBucket: 'wanderlense-pc.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ3GFI7QDrBO18XIdoXJ8wFb2d18gIRQQ',
    appId: '1:414659217522:web:a61c87aacf51fd49bb1aeb',
    messagingSenderId: '414659217522',
    projectId: 'wanderlense-pc',
    authDomain: 'wanderlense-pc.firebaseapp.com',
    storageBucket: 'wanderlense-pc.firebasestorage.app',
    measurementId: 'G-MW8LVV1GRN',
  );
}
